import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'
import Navbar from "../components/Navbar";
import Whatsapp from "@/components/Whatsapp";
import Footer from "@/components/Footer"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Whatsapp/>
        <Footer/>
        </body>
      </Providers>
      
    </html>
  );
}
